spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

#DATASOURCE
#spring.datasource.url=jdbc:postgresql://localhost:5432/avaliacoes
#spring.datasource.username=postgres
#spring.datasource.password=12345
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT}


#Hibernate
spring.jpa.hibernate.ddl-auto=create

#SECURITY
avaliacoes.security.token.secret=${SECRET}

